name: shell2telegram
version: '1.10'
summary: Telegram bot constructor from command-line
description: |
  Telegram bot constructor from command-line, written in Go.
  Settings through two command line arguments, bot-command and shell command.
grade: stable
confinement: strict
base: core18

parts:
  shell2telegram:
    plugin: go
    go-importpath: github.com/msoap/shell2telegram
    source: .
    source-type: git

apps:
  shell2telegram:
    command: bin/shell2telegram
    plugs: [network, home]
