name: shell2telegram
version: '1.8'
summary: Telegram bot constructor from command-line
description: |
  Telegram bot constructor from command-line, written in Go.
  Settings through two command line arguments, bot-command and shell command.
grade: stable
confinement: strict
base: core20

parts:
  shell2telegram:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/msoap/shell2telegram
  go:
    source-tag: go1.10

apps:
  shell2telegram:
    command: shell2telegram
    plugs: [network, home]
